{% set name = "parsl" %}
{% set version = "2023.6.12" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parsl-{{ version }}.tar.gz
  sha256: d7c98a7a0217a3c582733b0c2e8558bc69ae59b9abf462380eeef649cee15c13

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

outputs:
  - name: {{ name }}
    script: install_parsl.sh
    build:
      noarch: python
      entry_points:
        - parsl-globus-auth=parsl.data_provider.globus:cli_run
        - parsl-visualize=parsl.monitoring.visualization.app:cli_run
        - parsl-perf=parsl.benchmark.perf:cli_run

    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        # requirements.txt
        - pyzmq >=17.1.2
        - typeguard >=2.10,<3
        - typing-extensions
        - types-paramiko
        - types-requests
        - types-six
        - six
        - globus-sdk
        - dill
        - tblib
        - requests
        - paramiko
        - psutil >=5.5.1
        - setproctitle

    test:
      requires:
        - pip
      imports:
        - parsl
      commands:
        - pip check

  - name: {{ name }}-with-monitoring
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - sqlalchemy >=1.3.0,<2
        - pydot
        - networkx >=2.5,<2.6
        - flask >=1.0.2
        - flask-sqlalchemy
        - pandas <2
        - plotly
        # 3.0.1 has a build without proper constraints on setuptools
        - python-daemon !=3.0.1

    test:
      imports:
        - parsl
        - parsl.monitoring
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-with-aws
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - boto3
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-with-kubernetes
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - kubernetes
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - pip

# oauth-ssh not on conda-forge
#  - name: {{ name }}-with-oauth_ssh
#    build:
#      noarch: python
#    requirements:
#      host:
#        - python >=3.7
#      run:
#        - python >=3.7
#        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
#        - oauth-ssh >=0.9
#    test:
#      imports:
#        - parsl
#      commands:
#        - pip check
#      requires:
#        - pip

  - name: {{ name }}-with-google_cloud
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - google-auth
        - google-api-python-client
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-with-gssapi
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - python-gssapi
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - pip

# azure 3.0.0 was not built for linux
#  - name: {{ name }}-with-azure
#    build:
#      noarch: python
#    requirements:
#      host:
#        - python >=3.7
#      run:
#        - python >=3.7
#        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
#        - azure <=4
#        - msrestazure
#    test:
#      imports:
#        - parsl
#      commands:
#        - pip check
#      requires:
#        - pip

  - name: {{ name }}-with-workqueue
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - ndcctools
        # there is no work_queue pypi or conda-forge package
        # - work_queue
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-with-flux
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - pyyaml
        - cffi
        - jsonschema
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/Parsl/parsl
  license: Apache-2.0
  license_file: LICENSE
  summary: Simple parallel workflows system for Python

  description: |
    Parsl is a Python library for programming and executing 
    data-oriented workflows (dataflows) in parallel.
  doc_url: https://parsl.readthedocs.io/
  dev_url: https://github.com/Parsl/parsl

extra:
  recipe-maintainers:
    - ZhuozhaoLi
    - yadudoc
    - xylar
