{% set name = "parsl" %}
{% set version = "2025.11.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parsl-{{ version }}.tar.gz
  sha256: b3412b5582aefddaf061e8c3dd3f5e2ce0da6938df4889b53f0467f3be142f12

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

outputs:
  - name: {{ name }}
    script: install_parsl.sh
    build:
      noarch: python
      entry_points:
        - parsl-globus-auth=parsl.data_provider.globus:cli_run
        - parsl-visualize=parsl.monitoring.visualization.app:cli_run
        - parsl-perf=parsl.benchmark.perf:cli_run

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        # requirements.txt
        - pyzmq >=17.1.2
        - typeguard >=2.10,!=3.*,<5
        - typing-extensions
        - dill
        - tblib
        - requests
        - sortedcontainers
        - psutil >=5.5.1
        - setproctitle
        - filelock >=3.13,<4

    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - parsl
      commands:
        - pip check

  - name: {{ name }}-with-monitoring
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - sqlalchemy >=2,<2.1

    test:
      imports:
        - parsl
        - parsl.monitoring
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-visualization
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - {{ name }}-with-monitoring
        - pydot >=1.4.2
        - networkx >=3.2,<3.3
        - flask >=1.0.2
        - flask-sqlalchemy
        - pandas >=2.2,<3
        - plotly
        # 3.0.1 has a build without proper constraints on setuptools
        - python-daemon !=3.0.1

    test:
      imports:
        - parsl
        - parsl.monitoring
      commands:
        - pip check
        - parsl-visualize --help
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-aws
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - boto3
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-kubernetes
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - python-kubernetes
    test:
      imports:
        - parsl.providers.kubernetes.kube
        - kubernetes
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-google_cloud
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - google-auth
        - google-api-python-client
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-gssapi
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - python-gssapi
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

# azure 3.0.0 was not built for linux
#  - name: {{ name }}-with-azure
#    build:
#      noarch: python
#    requirements:
#      host:
#        - python {{ python_min }}
#      run:
#        - python >={{ python_min }}
#        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
#        - azure <=4
#        - msrestazure
#    test:
#      imports:
#        - parsl
#      commands:
#        - pip check
#      requires:
#        - python {{ python_min }}
#        - pip

  - name: {{ name }}-with-workqueue
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - ndcctools
        # there is no work_queue pypi or conda-forge package
        # - work_queue
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-flux
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - pyyaml
        - cffi
        - jsonschema
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-proxystore
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - proxystore
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-radical-pilot
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - radical.pilot 1.90
        - radical.utils 1.90
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-globus_compute
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - globus-compute-sdk >=2.34.0
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-globus_transfer
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - globus-sdk
    test:
      imports:
        - parsl
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

about:
  home: https://github.com/Parsl/parsl
  license: Apache-2.0
  license_file: LICENSE
  summary: Simple parallel workflows system for Python

  description: |
    Parsl is a Python library for programming and executing 
    data-oriented workflows (dataflows) in parallel.
  doc_url: https://parsl.readthedocs.io/
  dev_url: https://github.com/Parsl/parsl

extra:
  recipe-maintainers:
    - ZhuozhaoLi
    - yadudoc
    - xylar
